
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xcf`#,<\x9a\xac@N+\x0b7\x0fg\xa2\x12'

_lr_action_items = {'LPARENT':([1,3,18,21,],[7,-12,24,-12,]),'EQUALITY':([19,21,],[26,-15,]),'ASSIGN':([13,],[15,]),'INEQUALITY':([19,21,],[25,-15,]),'COMMA':([9,10,11,14,17,20,27,28,29,30,31,],[-14,12,-15,12,22,-8,22,12,-11,-10,-9,]),'RPARENT':([9,10,11,14,28,],[-14,13,-15,-13,31,]),'ID':([0,2,5,6,7,8,12,15,16,22,23,24,25,26,],[3,-2,3,-3,11,3,11,21,-5,21,-6,11,11,11,]),'DOT':([11,13,17,20,27,29,30,31,],[-15,16,23,-8,-7,-11,-10,-9,]),'$end':([2,4,5,6,8,16,23,],[-2,0,-1,-3,-4,-5,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'elements':([7,12,24,],[10,14,28,]),'goal':([15,22,],[17,27,]),'factname':([0,5,8,15,22,],[1,1,1,18,18,]),'rule':([0,5,8,],[2,2,2,]),'element':([7,12,15,22,24,25,26,],[9,9,19,19,9,29,30,]),'program':([0,],[4,]),'fact':([0,5,8,],[6,6,6,]),'goalRule':([15,22,],[20,20,]),'block':([0,5,8,],[5,8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('program',1,'p_program','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',23),
  ('block',1,'p_block1','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',28),
  ('block',1,'p_block2','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',32),
  ('block',2,'p_block3','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',36),
  ('fact',5,'p_fact','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',40),
  ('rule',7,'p_rule','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',45),
  ('goal',3,'p_goal1','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',50),
  ('goal',1,'p_goal2','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',55),
  ('goalRule',4,'p_goalrule1','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',60),
  ('goalRule',3,'p_goalrule2','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',65),
  ('goalRule',3,'p_goalrule3','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',70),
  ('factname',1,'p_factname','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',75),
  ('elements',3,'p_elements1','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',80),
  ('elements',1,'p_elements2','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',85),
  ('element',1,'p_element','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',90),
  ('empty',0,'p_empty','E:\\Workspace\\git\\Interprete\\Intenprete\\src\\analizadorSintactico.py',96),
]
